name: Benchmarks
on:
  schedule:
    - cron: '0 1 * * *' # nightly build
  workflow_dispatch:

jobs:

  benchmark:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set Java up in the runner
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: 8
      - name: Install missing dependencies to container
        run: |
          sudo apt update
          sudo apt install -y stunnel make git gcc
      - name: Maven offline
        run: |
          mvn -q dependency:go-offline
      - name: Clean environment
        run: |
          make cleanup
        env:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      - name: Start servers
        run: |
          make start
      - name: Run benchmarks
        run: |
          mvn -Pjmh clean test
        env:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      # Run `github-action-benchmark` action
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'jmh'
          # Where the output from the benchmark tool is stored
          output-file-path: benchmark.log
          # Where the previous data file is stored
          external-data-json-path: ./cache/benchmark.log
          # Workflow will fail when an alert happens
          fail-on-alert: true
      # Upload the updated cache file for the next job by actions/cache
