name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.rst'
    branches:
      - main
      - '[0-9].*'
  pull_request:
    branches:
      - main
      - '[0-9].*'
  schedule:
    - cron: '0 1 * * *' # nightly build
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        redis_version:
          - "unstable"
          - "8.0"
          - "7.4"
          - "7.2"
    env:
      REDIS_ENV_WORK_DIR: ${{ github.workspace }}/work

    steps:
      - name: Test Redis Server Version
        id: map-tags
        run: |
          # Map requested version to github or  tag
          case "${{ matrix.redis_version }}" in
            "unstable") redis_branch="unstable" stack_version="8.0-M04-pre" redis_test_version="8.0-M02";;
            "8.0") redis_branch="8.0" stack_version="8.0-M04-pre" ;;
            "7.4") redis_branch="7.4" stack_version="rs-7.4.0-v2" ;;
            "7.2") redis_branch="7.2" stack_version="rs-7.2.0-v14" ;;
            *) echo "Unsupported version: ${{ matrix.redis_version }}" && exit 1 ;;
          esac
          # Save them as outputs for later use
          echo "redis_branch=$redis_branch" >> $GITHUB_OUTPUT
          echo "redis_stack_version=$stack_version" >> $GITHUB_OUTPUT
          echo "redis_test_version=$redis_test_version" >> $GITHUB_OUTPUT
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set Java up in the runner
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: 8
      - name: Install missing dependencies to container
        run: |
          sudo apt update
      - name: Set up Docker Compose environment
        run: |
          mkdir -m 777 $REDIS_ENV_WORK_DIR
          export REDIS_VERSION="${{ steps.map-tags.outputs.redis_test_version }}"
          make docker-start version=$REDIS_VERSION
      - name: Maven offline
        run: |
          mvn -q dependency:go-offline
      - name: Clean environment
        run: |
          make clean
        env:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      - name: Tear down Docker Compose environment
        run: |
          docker compose $COMPOSE_ENV_FILES -f src/test/resources/env/docker-compose.yml down
        continue-on-error: true
      - name: Run tests
        run: |
          make docker-test
        env:
          REDIS_STACK_VERSION: ${{ steps.map-tags.outputs.redis_stack_version }}
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test failure reports to Codecov
        uses: codecov/test-results-action@v1
        if: always() # always upload test results to include test failures
        with:
          fail_ci_if_error: false
          files: ./target/surefire-reports/TEST*,./target/failsafe-reports/TEST*
          verbose: ${{ runner.debug }}
          token: ${{ secrets.CODECOV_TOKEN }}
